#' @title The Frequon (Frequency Analysis) Game
#'
#' @description
#' The \code{frequon} function is used for solving problems in the data-based game ,,The Frequon Game''.
#'
#' @param ... \code{frequon} function is called by different arguments, which vary depending
#' on a problem that Bit is trying to solve. See \code{Details} in order to learn more about the list of possible arguments.
#'
#' @details Every time when some additional hints are needed one should add
#' \code{hint=TRUE} argument to the \code{proton} function.
#'
#' In order to get more information about a user on the Proton server
#' one should pass \code{action = "login"}, \code{login="XYZ"} arguments
#' to the \code{proton} function.
#'
#' In order to log into the Proton server one should pass \code{action = "login"},
#' \code{login="XYZ"}, \code{password="ABC"} arguments to the \code{proton} function.
#' If the password matches login, then one will receive a message about successful login.
#'
#' In order to log into a server different from Proton one should pass
#' \code{action = "server"}, \code{host="XYZ"} arguments to the \code{proton} function.
#'
#' ,,The Frequon Game'' is a free of charge, educational project of the SmarterPoland.pl Foundation.
#'
#' @author
#' Katarzyna Fak - the idea and the implementation,
#' Przemyslaw Biecek - comments and the integration with this package.
#'
#' @examples
#' \dontrun{
#' frequon()
#' frequon(hint=TRUE)
#' }
#' @rdname frequon
#' @export
frequon <- function(...) {
 args <- list(...)

 txt <- structure(c("uILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nhFYQVXG: bLF NZB YV RMGVIVHGVW\n\nkVDMZ TIFKZ (MZADZć) NZ KILYOVN.\nnFHR HRę WLHGZć WL SZHłZ ANZIłVTL KIABQZXRVOZ YB XLśGZN.\naLHGZłB KL MRN... 3  DRZWLNLśXR: `TFMH`, `ZMW` LIZA `ILHVH`,\nWL PGóIBXS MRV NZQą WLHGęKF, ZOV KLWVQIAVDZQą, żV D GBXS\nDRZWLNLśXRZXS NLżV YBć XLś RMGVIVHFQąXVTL. aDIZXZQą HRę WL xRVYRV\nA KLNLXą, TWBż HłBHAVOR, żV QVHGVH WLYIB D ILADRąABDZMRF GZPRXS\nKILYOVNóD.\n\nxAB AVXSXVHA WLłąXABć WL AVHKLłF R KLNóX RN D ILADRąAZMRF GVTL\nKILYOVNF?\n\nrU BLF DZMG GL SVOK, KOVZHV GBKV:\n`UIVJFLM(HFYQVXG = \"iV: zHPRMT ULI SVOK\", XLMGVMG = \"gVCG LU GSVHV NVHHZTVH BLF SZEV ZXXVHH GL\")`\nHL ZH DV XLFOW IVZW GSV NVHHZTV GLL.\n\niVNVNYVI: ZMB GRNV BLF DZMG, BLF XZM TVG HLNV KRVXV LU ZWERXV, QFHG\nGBKV: `UIVJFLM(SRMG=gifv)`.\n",
             "uILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nhFYQVXG: uIVJFVMXRVH\n\ndV ZIV HL TOZW BLF DZMG GL SVOK FH!\n\ngSZMP BLF ULI GSV NVHHZTV, RG OLLPH RMGVIVHGRMT... sLDVEVI, GSRH GVCG\nRH GL OLMT GL YV LMV KZHHDLIW DV ZIV HVVPRMT. gSRH NFHG YV HLNV XLWVW\nNVHHZTV, RU LMOB DV XLFOW PMLD GSV PVB...\n\nyFG OVG`H GZPV Z OLLP, GSV `K` OVGGVI ZKKVZIH EVIB LUGVM. zMW\n`R` WLVH`G. rM VMTORHS OZMTFZTV OVGGVI `V` DLFOW LXXFIVH\nNLHG LUGVM. rU DV DLFOW PMLD SLD LUGVM VZXS OVGGVI RH FHVW RM\nGSV NVHHZTV, DV XLFOW XLNKZIV GSVN DRGS PMLDM VMTORHS\nOVGGVI UIVJFVMXRVH! hL OVG`H GL GSRH!\n\ndV ZIV TLRMT GL KIVKZIV WZGZ ZYLFG UIVJFVMXRVH LU OVGGVIH\nRM VMTORHS, HL RU BLF XLFOW URMW GSV UIVJFVMXRVH RM GSV NVHHZTVH,\nGSZG DLFOW YV ZDVHLNV (GL GIAVYZ ANRVMRX :k).\n\nhVMW FH IVKOB: `UIVJFLM(HFYQVXG = \"iV: uIVJFVMXRVH\", XLMGVMG = `UIVJ`)` ZH HLLM ZH BLF\nDROO URMRHS. `UIVJ` RH GSV EVXGLI LU UIVJFVMXRVH ULI VZXS OVGGVI.\nkOVZHV, IVNVNYVI GL MZNV GSRH EVXGLI DRGS IVHKVXGREV OVGGVIH!\n",
             "uILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nhFYQVXG: gIZMHXIRKGRLM\n\ntIVZG QLY! mLD, DSVM DV PMLD DSRXS OVGGVIH ZIV FHVW NLHG LUGVM\nZMW DSRXS ZIV GSV OVZHG XLNNLM, DV XZM XLNYRMV GSVN DRGS PMLDM\nVMTORHS UIVJFVMXRVH LU OVGGVIH. dV SZEV KIVKZIVW ZMW ZGGZXSVW\nGSV `vMTORHSoVGGVIuIVJFVMXB` WZGZHVG. rG XLMGZRMH IVOZGREV\nUIVJFVMXRVH LU OVGGVIH RM GSV VMTORHS OZMTFZTV.\n\nmLD BLF XZM HFYHGRGFGV LOW XRKSVIVW OVGGVIH DRGS GSV MVD\nVMTORHS OVGGVIH. xZM BLF HSLD FH BLFI IVHFOGH?\n\nhVMW FH IVKOB: `UIVJFLM(HFYQVXG = \"iV: gIZMHXIRKGRLM\", XLMGVMG = \"GVCGBLFDROOTVG\")`.\ndV DRHS BLF OFXP!\n\nyVHG IVTZIWH!\n",
             "uILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nhFYQVXG: pVB\n\ndVOO WLMV! mLD DV ZIV HL XOLHV! lFI NVHHZTV OLLPH Z ORGGOV YRG UZNRORZI,\nGSVIV ZIV VEVM HLNV DLIWH DV PMLD. yFG GSVIV ZIV ZOHL HGROO DLIWH,\nOLLPRMT HGIZMTV. rG NVZMH GSZG LFI PVB RH MLG UFOOB\nXLIIVXG, ZMW DV MVVW GL RMEVHGRTZGV GSVHV OVGGVIH, GSZG DVIV\nNRHGIZMHOZGVW.\n\ngSVIV RH LMV RWVZ SLD GL WL GSRH.\n\naORXANB DHABHGPRV DBIZAB, GV, PGóIV KLQZDRZQą HRę MZQXAęśXRVQ HZ WOZ MZH łZGDV WL\nKLKIZDRVMRZ. gV PGóIV KLQZDRZQą HRę MZQIAZWARVQ YBć NLżV Hą łZGDL ILAKLAMZDZOMBNR\nIAVXALDMRPZNR?\n\ngZPV ZWEZMGZTV LU `GLK100XLNNLMdLIWH`.\n\ngBKV:\n`UIVJFLM( HFYQVXG=\"iV: pVB\", XLMGVMG=X(LOW = \"ZYXWVU....A\", MVD = \"MVDOVGGVIHIVHKVXGREVOB\"))`\nDSVIV `LOW` ZIV GSV OVGGVIH RM GSV XLWV`H HVMHV ZMW `MVD` ZIV URGGVW IVZO OVGGVIH.\n",
             "uILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nhFYQVXG: mVCG GVCG\n\nvCXVOOVMG DLIP, BLF SZEV XIZXPVW GSV XLWV!\n\nsLDVEVI GSVIV RH ML KZHHDLIW RM SVIV.\ngSVIV NFHG YV HLNV XOFV RM GSRH NVHHZTV...\n\ndSZG WL BLF GSRMP ZYLFG KLHHRYRORGB GSZG LFI UIRVMW FHVW GSV PVB\nGL XRKSVIV GSV MZNVH LU GDL IVNZRMRMT NVHHZTVH?\ndLFOW BLF SZEV ZXXVHH GL GSVN MLD?\n\nkOVZHV, HVMW FH IVKOB:\n`UIVJFLM(HFYQVXG = \"iV: mVCG GVCG: c\",\n          XLMGVMG = \"xLMGVMG LU GSV FMOLXPVW NVHHZTV\")`\n\nDSVIV \"c\" RH GSV MZNV LU GSZG NVHHZTV BLF ZIV ZYOV GL FMOLXP.\n\ndV DLFOW YV TIZGVUFO.\n",
             "uILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nhFYQVXG: oVMTGSH RM GSV GVCG\n\nlYERLFHOB GSRH NVHHZTV RH ZOHL XRKSVIVW. dV GIRVW GL FHV GSV PVB\nYFG GFIMH LFG RG DZH DIRGGVM RM HLNV OZMTFZTV DV FMULIGFMZGVOOB WLM`G PMLD.\nxZM BLF IVXLTMRAV GSV OZMTZTFV?\n\nwLM`G DLIIB, DV PMLD HLNV HRNKOV RWVZ SLD GL IVXLTMRAV GSV OZMTFZTV LU GSV ZMB\nXRKSVIVW NVHHZTV. zOO BLF MVVW GL WL RH GL NVZHFIV GSV OVMTGS LU VZXS DLIW. rU DV DLFOW\nPMLD SLD NZMB DLIWH SZH GSV OVMTGS LU 1, 2, 3, ZMW HL LM, DV XLFOW XLNKZIV\nGSVN DRGS GSV OVMTGSH LU DLIWH RM OZMTFZTVH GSZG DV PMLD! mZGFIZOOB DV MVVW HLNV\nSFTV ZNLFMG LU DLIWH RM KOVMGB OZMTFZTVH. rG`H QFHG ZH DVOO DV SZEV Z HZNKOV UILN\nDRPRKVWRZ IVHLFIXVH, HL DV XZM HSZIV RG DRGS BLF.\nkOVZHV, URMW GSV `DRPRJFLGVH` ZGGZXSNVMG. gSVIV RH Z ORHG LU JFLGVH ULI NZMB OZMTFZTVH.\ndV SLKV GSRH RH VMLFTS ULI LFI MVVWH.\n\ngSRH RH SFTV QLY GL NVZHFIV GSV OVMTGS LU VZXS DLIW ULI ZOO OZMTFZTVH, YFG DV YVORVEV\nBLF PMLD HLNV UZHG DZB GL (.... XLś YBOV MRV WL GSRH).\n\nhVMW FH BLFI IVHFOGH:\n`UIVJFLM(HFYQVXG=\"iV: oVMTGSH RM GSV GVCG\", XLMGVMG = `OVMTGSH`, ZGGZXSNVMG = `DRPR_OVMTGSH`)`.\n`OVMTGSH` RH GSV EVXGLI LU GZYVOVW OVMTGS LU ZOO DLIWH.\n`DRPR_OVMTGSH` RH GSV ORHG LU GZYVOVW OVMTGS LU ZOO DLIWH ULI VZXS OZMTFZTV.\nkOVZHV, IVNVNYVI GL MZNV GSRH ORHG DRGS IVHKVXGREV OZMTFZTVH!\n\ngSZMPH GL GSRH WZGZ DV DLFOW YV ZYOV GL KIVKZIV XLFKOV YZIKOLGH GL XLMXOFWV ZYLFG\nGSV HRNROZIRGRVH YVGDVVM WRHGIRYFGRLM LU GSV OVMTGSH RM LFI NVHHZTV ZMW PMLDM OZMTFZTVH.\n",
             "uILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nhFYQVXG: oZMTFZTV RM GSV NVHHZTV\n\ndVOO WLMV! gSZMPH GL BLFI IVHFOGH DV LYGZRM VCXVOOVMG YZIKOLGH (BLF XZM KILYZYOB\nZOHL HVV GSVN RM BLFI NZTRX KILTIZN :k). mLD DV XZM RMEVHGRTZGV\nDSZG GSV OZMTFZTV DZH FHVW GL KIVKZIV GSV HVXLMW NVHHZTV.\nsLD WL BLF GSRMP: DSRXS UILN GSV ZOO WRHGIRYFGRLMH RH NLHG HRNROZI GL\nGSV WRHGIRYFGRLM LU GSV OVMTGSH RM LFI NVHHZTV?\n\nhVMW FH BLFI GSLFTSGH! gBKV\n`UIVJFLM(HFYQVXG = \"iV: oZMTFZTV RM ZMW NVHHZTV\", XLMGVMG = \"oZMTFZTV\")`\nDSVIV \"oZMTFZTV\" RH GSV MZNV LU GSV IRTSG OZMTFZTV.\n",
             "uILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nhFYQVXG: kZHHDLIW\n\ngZP GVż R MZN HRę DBWZQV. ŚDRVGMZ ILYLGZ, GVIZA AMZNB POFXA, AMZNB QęABP...\nnLżV AZMRN AZXAMRVNB GłFNZXABć Gę DRZWLNLść, HKIóYFQNB FABHPZć WLHGęK\nWL LHGZGMRVQ GSV `TFMH`. dRVNB, żV MZHA KIABQZXRVO OFYR DBPLIABHGBDZć\nPOFXA QVWMVQ AZTZWPR WL PLWLDZMRZ MZADB RMMVQ, DRęX NLżV R GBN IZAVN...\nxAB DRVHA, QZP QVHG KL hłLDVńHPF `TFMH`?\n\nnB AZQNFQVNB HRę GłFNZXAVMRVN DRZWLNLśXR. qVśOR AMZQWARVHA XLś RMGVIVHFQąXVTL\nD GIAVXRVQ A MZHABXS DRZWLNLśXR, KILHRNB, WZQ MZN AMZć!\n\n`UIVJFLM(HFYQVXG = \"iV: kZHHDLIW\", XLMGVMG = \"GSVkZHHDLIWbLFdROOuRMW\")`.\n",
             "uILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nhFYQVXG: bLF ZIV GSV XSZNKRLM!\n",
             "uRIHGOB GIB GL ZMHDVI GSV ULOOLDRMT JFVHGRLMH:\n  * wLVH i GIVZG \"z\" ZMW \"Z\" ZH GSV HZNV OVGGVI?\n  * rH \"DLIW\" ZMW \"DLIW,\" GSV HZNV DLIW ULI i?\n\ngSV UFMXGRLMH ORPV: \"GLOLDVI()/GLFKKVI()\", \"THFY()\" NRTSG YV FHVUFOO GL SZMWOV GSVHV RHHFVH. xLMHRWVI IVKOZXRMT ZOO MLM-ZOKSZMFNVIRX  XSZIZXGVIH DRGS VNKGB HGIRMTH (\"\").\ngSV VZHRVHG DZB GL WVZO DRGS GSVHV PRMWH LU KILYOVN RH GL FHV IVTVC. hGIRMT: \"[^Z-A ]\" ZOOLDH BLF GL VCGIZXG ZOO MLM-OVGGVI XSZIZGVIH DRGS HKZXVH.\n\nuRMZOOB UZNRORZIRAV BLFIHVOU DRGS \"HGIHKORG()\" ZMW \"GZYOV()\" GL XLFMG ZOO OVGGVIH VZHROB.\ngSV `OVGGVIH` i-LYQVXG NZB ZOHL YV EVIB SVOKUFO ULI GSV KILYOVN.\n\ngL HVV DSLHV OVGGVIH LXXFIV NLHG UIVJFVMGOB FHV `HLIG()`.\n",
             "nZMFZO HFYHRGFGRLM NZB YB KIVGGB OZYLFIRLFH, GSZG RH DSB BLF KILYZYOB WL ZKKIRVXRZGV Z `XSZIGI()` UFMXGRLM :) iVNVNYVI GL XLMEVIG ZOO OVGGVIH GL OLDVIXZHVH.\n",
             "zOO BLF MVVW RH GL HKORG ZOO GVCG YB HKZXVH ZMW GZYOV ZOO XIVZGVW DLIWH. wL BLF IVNVNYVI SLD `HGIHKORG()` DLIP?\n\nrU BLF WRW GSRH, GIB GL KFG LOW OVGGVIH RM ZOKSZYVGRXZO LIWVI.\n",
             "iVNVNYVI GSZG RU DV SZEV `LOW` ZH XRKSVIVW ZMW `MVD` ZH IVZO OVGGVIH, DV MVVW GL URMW  IVZO OVGGVIH RM `MVD` ZMW HVVPRMT GSVRI GIZMHOZGRLM RM GSV `LOW` XSZIZXGVI HGIRMT.\n",
             "gSVIV RH Z EVIB FHVUFO UFMXGRLM RM i GL NVZHFIV MFNYVI LU XSZIZXGVIH RM DLIWH. gZPV ZWEZMGZTV LU `MXSZI()` UFMXGRLM. iVNVNYVI GL HKORG GSV HGIRMT RMGL\\MHRMTOV DLIWH DRGS `HGIHKORG()` ZH BLF WRW RG YVULIV. gL NVZHFIV GSV OVMTGS\\MLU VZXS DLIWH XLIIVXGOB DZGXS ZOO XLNZH ZMW WLGH! wLVH GSV OVMTGS LU \"WLGH.\" ZMW \"WLGH\" RH GSV HZNV? `THFY()` UFMXGRLM DRGS \"[^Z-A ]\" IVTVC NZB YV SVOKUFO SVIV\\M(YFG LMOB RU BLF XLMEVIG BLFI GVCG GL OLDVIXZHV!).\n\nwL GSV HZNV DRGS ZOO VOVNVMGH LU `DRPRJFLGVH` ORHG. bLF NZB FHV `ULI` OLLK LI VEVM `OZKKOB` UFMXGRLM GL WL GSRH VZHRVI ZMW UZHGVI!\n",
             "xLNKZIV WRHGIRYFGRLMH FHRMT `YZIKOLG()` UFMXGRLM ULI XLFMGVW OVMTGSH LU DLIWH RM \\MGSV NVHHZTV ZMW XLFMGVW OVMTGSH LU DLIWH RM ZOO OZMTFZTVH.\n",
             "dV DVIV OLLPRMT HL OLMT ULI HLNVYLWB ORPV BLF, DSL XLFOW\nSVOK FH GL HLOEV GSRH NRHGVIB. rU BLF WLM`G SZEV ZXXVHH GL GSV\nNVHHZTVH, GSZM DV MVVW GL ZHP HLNVLMV VOHV :(\n",
             "mRXV GIB, YFG GSVIV ZIV LMV LI NLIV NRHHRMT EZOFVH (mz) RM TREVM EVXGLI.\nuROO ZOO GSV mzH ZMW GSVM GIB GL KZHH GSV EVXGLI ZTZRM.\n",
             "gSVIV RH HLNVGSRMT DILMT DRGS TREVM UIVJFVMXRVH... sZEV BLF XLMEVIGVW GVCG GL\nOLDVIXZHV? zIV BLF HFIV BLF WRW GSRH IRTSG?\n",
             "gSV EVXGLI BLF SZEV KZHHVW WLVH MLG XLMGZRM MZNVH. kOVZHV, KZHH MZNVW EVXGLI.\n",
             "bLF WRW MLG KZHH UIVJFVMXRVH ULI ZOO OVGGVIH :(\n", "gSRH GIZMHOZGRLM HVVNH GL WLVHM`G URG GL GSV `ILHVH`.\nwRW BLF HLIGVW `UIVJ` EVXGLI YVULIV GIZMHOZGRLM XLIIVXGOB?\n",
             "dV WLM'G FMWVIHGZMW GSV `PVB` EZOFV RM TREVM ULIN. gBKV ZTZRM GSV PVB BLF ULFMW RM GSV\nULOOLDRMT ULIN: X(LOW = 'LOWOVGGVIHZYXW...A', MVD = 'MVDOVGGVIHIVHKVXGREVOB')\n",
             "wLM`G BLF GSRMP, GSZG OVMTGSH LU `LOW` ZMW `MVD` YLGS HSLFOW YV VJFZO GL 26?\ngSRH RH GSV MFNYVI LU ZOO OVGGVIH RM oZGRM ZOKSZYVG.\n\nkOVZHV, XLIIVXG GSRH NRHGZPV ZMW GIB ZTZRM.\n",
             "mRXV GIB, SLDVEVI GSRH PVB WLVH MLG GIZHOZGV GSV NVHHZTV XLIIVXGOB.\nzIV BLF HFIV VEVIBGSRMT RH ZOO IRTSG?\n",
             "zXXLIWRMT GL GSV LFI URIHG LFI IVNZRMRMT NVHHZTVH ZIV MZNVW \"TFMH\" ZMW \"ZMW\".\nHL c HSLFOW YV LMV UILN GSVHV MZNVH.\n",
             "sZEV BLF IVZOOB FMOLXPVW GSV \"TFMH\" NVHHZTV?\n", "dV XZMMLG LKVM GSV NVHHZTV. gIB ZTZRM, NZBYV BLF HVMW Z YZW UROV?\n",
             "mZNVH LU ZGGZXSNVMG WLM`G NZGXS. kOVZHV, HVMW FH `OVMTGSH` DRGS MZNVH ZXXLIWZMG\nDRGS `DRPRJFLGVH` MZNVH.\n",
             "gSVIV RH HLNVGSRMT DILMT DRGS GSV NVGSLW BLF XLFMG OVMTGS LU DLIWH RM GSV NVHHZTV\nLI `DRPRJLFGVH` UROV. kOVZHV, GIB ZTZRM.\n",
             "dV WLM`G GSRMP GSRH RH GSV IRTSG ZMHDVI. gSV OZMTFZTV BLF KILKLHVW WLVHM`G URG GL\nLFI NVHHZTV.\n",
             "dV ZUIZRW GSRH RH MLG GSV KZHHDLIW DV ZIV OLLPRMT ULI. zIV BLF HFIV GSVIV RH MLGSRMT\nVOHV GL HVV?\n",
             "rG HVVNH GSZG BLF NRTSG SZEV ULITLGGVM GL ZGGZXS UROVH. kOVZHV, HVMW GSRH NVHHZTV\nDRGS GSV ZGGZXSVNVMG.\n",
             "hVMW GSRH NVHHZTV DRGSLFG XLMGVMG?\n", "wL bLF dZMG GL hVMW gSRH nVHHZTV dRGSLFG Z hFYQVXG?\n\n## gzhp: VIILIhFYQVXG\n\nhVMW GSRH NVHHZTV DRGSLFG XLMGVMG?\n\n## gzhp: VIILIxLMGVMG\n\nDRGS GSV ZGGZXSVNVMG.\nrG HVVNH GSZG BLF NRTSG SZEV ULITLGGVM GL ZGGZXS UROVH. kOVZHV, HVMW GSRH NVHHZTV\n\n## gzhp: VIILIzGGZXSNVMG\n\nVOHV GL HVV?\ndV ZUIZRW GSRH RH MLG GSV KZHHDLIW DV ZIV OLLPRMT ULI. zIV BLF HFIV GSVIV RH MLGSRMT\n\n## gzhp: VIILIvMW\n\nLFI NVHHZTV.\ndV WLM`G GSRMP GSRH RH GSV IRTSG ZMHDVI. gSV OZMTFZTV BLF KILKLHVW WLVHM`G URG GL\n\n## gzhp: VIILIoZMTFZTV\n\nLI `DRPRJLFGVH` UROV. kOVZHV, GIB ZTZRM.\ngSVIV RH HLNVGSRMT DILMT DRGS GSV NVGSLW BLF XLFMG OVMTGS LU DLIWH RM GSV NVHHZTV\n\n## gzhp: VIILIoVMTGSH\n\nDRGS `DRPRJFLGVH` MZNVH.\nmZNVH LU ZGGZXSNVMG WLM`G NZGXS. kOVZHV, HVMW FH `OVMTGSH` DRGS MZNVH ZXXLIWZMG\n\n## gzhp: VIILIdRPRmZNVH\n\ndV XZMMLG LKVM GSV NVHHZTV. gIB ZTZRM, NZBYV BLF HVMW Z YZW UROV?\n\n## gzhp: VIILIyZWzmw\n\nsZEV BLF IVZOOB FMOLXPVW GSV \"TFMH\" NVHHZTV?\n\n## gzhp: VIILIyZWc2\n\nHL c HSLFOW YV LMV UILN GSVHV MZNVH.\nzXXLIWRMT GL GSV LFI URIHG LFI IVNZRMRMT NVHHZTVH ZIV MZNVW \"TFMH\" ZMW \"ZMW\".\n\n## gzhp: VIILIyZWc\n\nzIV BLF HFIV VEVIBGSRMT RH ZOO IRTSG?\nmRXV GIB, SLDVEVI GSRH PVB WLVH MLG GIZHOZGV GSV NVHHZTV XLIIVXGOB.\n\n## gzhp: VIILIyZWpVB\n\nkOVZHV, XLIIVXG GSRH NRHGZPV ZMW GIB ZTZRM.\n\ngSRH RH GSV MFNYVI LU ZOO OVGGVIH RM oZGRM ZOKSZYVG.\nwLM`G BLF GSRMP, GSZG OVMTGSH LU `LOW` ZMW `MVD` YLGS HSLFOW YV VJFZO GL 26?\n\n## gzhp: VIILIpVB2\n\nULOOLDRMT ULIN: X(LOW = 'LOWOVGGVIHZYXW...A', MVD = 'MVDOVGGVIHIVHKVXGREVOB')\ndV WLM'G FMWVIHGZMW GSV `PVB` EZOFV RM TREVM ULIN. gBKV ZTZRM GSV PVB BLF ULFMW RM GSV\n\n## gzhp: VIILIpVB1\n\nwRW BLF HLIGVW `UIVJ` EVXGLI YVULIV GIZMHOZGRLM XLIIVXGOB?\ngSRH GIZMHOZGRLM HVVNH GL WLVHM`G URG GL GSV `ILHVH`.\n\n## gzhp: VIILIwVXRKSVI\n\nbLF WRW MLG KZHH UIVJFVMXRVH ULI ZOO OVGGVIH :(\n\n## gzhp: VIILIoVGGVIH\n\ngSV EVXGLI BLF SZEV KZHHVW WLVH MLG XLMGZRM MZNVH. kOVZHV, KZHH MZNVW EVXGLI.\n\n## gzhp: VIILImLmznvh\n\nOLDVIXZHV? zIV BLF HFIV BLF WRW GSRH IRTSG?\ngSVIV RH HLNVGSRMT DILMT DRGS TREVM UIVJFVMXRVH... sZEV BLF XLMEVIGVW GVCG GL\n\n## gzhp: VIILIuIVJFVMXRVH\n\nuROO ZOO GSV mzH ZMW GSVM GIB GL KZHH GSV EVXGLI ZTZRM.\nmRXV GIB, YFG GSVIV ZIV LMV LI NLIV NRHHRMT EZOFVH (mz) RM TREVM EVXGLI.\n\n## gzhp: VIILImzH\n\nNVHHZTVH, GSZM DV MVVW GL ZHP HLNVLMV VOHV :(\nSVOK FH GL HLOEV GSRH NRHGVIB. rU BLF WLM`G SZEV ZXXVHH GL GSV\ndV DVIV OLLPRMT HL OLMT ULI HLNVYLWB ORPV BLF, DSL XLFOW\n\n## gzhp: VIILIrMGIL\n\nxLNKZIV WRHGIRYFGRLMH FHRMT `YZIKOLG()` UFMXGRLM ULI XLFMGVW OVMTGSH LU DLIWH RM \\MGSV NVHHZTV ZMW XLFMGVW OVMTGSH LU DLIWH RM ZOO OZMTFZTVH.\n\n## gzhp: SRMG7\n\nwL GSV HZNV DRGS ZOO VOVNVMGH LU `DRPRJFLGVH` ORHG. bLF NZB FHV `ULI` OLLK LI VEVM `OZKKOB` UFMXGRLM GL WL GSRH VZHRVI ZMW UZHGVI!\n\ngSVIV RH Z EVIB FHVUFO UFMXGRLM RM i GL NVZHFIV MFNYVI LU XSZIZXGVIH RM DLIWH. gZPV ZWEZMGZTV LU `MXSZI()` UFMXGRLM. iVNVNYVI GL HKORG GSV HGIRMT RMGL\\MHRMTOV DLIWH DRGS `HGIHKORG()` ZH BLF WRW RG YVULIV. gL NVZHFIV GSV OVMTGS\\MLU VZXS DLIWH XLIIVXGOB DZGXS ZOO XLNZH ZMW WLGH! wLVH GSV OVMTGS LU \"WLGH.\" ZMW \"WLGH\" RH GSV HZNV? `THFY()` UFMXGRLM DRGS \"[^Z-A ]\" IVTVC NZB YV SVOKUFO SVIV\\M(YFG LMOB RU BLF XLMEVIG BLFI GVCG GL OLDVIXZHV!).\n\n## gzhp: SRMG6\n\niVNVNYVI GSZG RU DV SZEV `LOW` ZH XRKSVIVW ZMW `MVD` ZH IVZO OVGGVIH, DV MVVW GL URMW  IVZO OVGGVIH RM `MVD` ZMW HVVPRMT GSVRI GIZMHOZGRLM RM GSV `LOW` XSZIZXGVI HGIRMT.\n\n## gzhp: SRMG5\n\nrU BLF WRW GSRH, GIB GL KFG LOW OVGGVIH RM ZOKSZYVGRXZO LIWVI.\n\nzOO BLF MVVW RH GL HKORG ZOO GVCG YB HKZXVH ZMW GZYOV ZOO XIVZGVW DLIWH. wL BLF IVNVNYVI SLD `HGIHKORG()` DLIP?\n\n## gzhp: SRMG4\n\nnZMFZO HFYHRGFGRLM NZB YB KIVGGB OZYLFIRLFH, GSZG RH DSB BLF KILYZYOB WL ZKKIRVXRZGV Z `XSZIGI()` UFMXGRLM :) iVNVNYVI GL XLMEVIG ZOO OVGGVIH GL OLDVIXZHVH.\n\n## gzhp: SRMG2\n\ngL HVV DSLHV OVGGVIH LXXFIV NLHG UIVJFVMGOB FHV `HLIG()`.\n\ngSV `OVGGVIH` i-LYQVXG NZB ZOHL YV EVIB SVOKUFO ULI GSV KILYOVN.\nuRMZOOB UZNRORZIRAV BLFIHVOU DRGS \"HGIHKORG()\" ZMW \"GZYOV()\" GL XLFMG ZOO OVGGVIH VZHROB.\n\ngSV VZHRVHG DZB GL WVZO DRGS GSVHV PRMWH LU KILYOVN RH GL FHV IVTVC. hGIRMT: \"[^Z-A ]\" ZOOLDH BLF GL VCGIZXG ZOO MLM-OVGGVI XSZIZGVIH DRGS HKZXVH.\ngSV UFMXGRLMH ORPV: \"GLOLDVI()/GLFKKVI()\", \"THFY()\" NRTSG YV FHVUFOO GL SZMWOV GSVHV RHHFVH. xLMHRWVI IVKOZXRMT ZOO MLM-ZOKSZMFNVIRX  XSZIZXGVIH DRGS VNKGB HGIRMTH (\"\").\n\n  * rH \"DLIW\" ZMW \"DLIW,\" GSV HZNV DLIW ULI i?\n  * wLVH i GIVZG \"z\" ZMW \"Z\" ZH GSV HZNV OVGGVI?\nuRIHGOB GIB GL ZMHDVI GSV ULOOLDRMT JFVHGRLMH:\n\n## gzhp: SRMG1\n\nhFYQVXG: bLF ZIV GSV XSZNKRLM!\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nuILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\n\n## gzhp: LFGIL\n\n`UIVJFLM(HFYQVXG = \"iV: kZHHDLIW\", XLMGVMG = \"GSVkZHHDLIWbLFdROOuRMW\")`.\n\nD GIAVXRVQ A MZHABXS DRZWLNLśXR, KILHRNB, WZQ MZN AMZć!\nnB AZQNFQVNB HRę GłFNZXAVMRVN DRZWLNLśXR. qVśOR AMZQWARVHA XLś RMGVIVHFQąXVTL\n\nxAB DRVHA, QZP QVHG KL hłLDVńHPF `TFMH`?\nPOFXA QVWMVQ AZTZWPR WL PLWLDZMRZ MZADB RMMVQ, DRęX NLżV R GBN IZAVN...\nWL LHGZGMRVQ GSV `TFMH`. dRVNB, żV MZHA KIABQZXRVO OFYR DBPLIABHGBDZć\nnLżV AZMRN AZXAMRVNB GłFNZXABć Gę DRZWLNLść, HKIóYFQNB FABHPZć WLHGęK\ngZP GVż R MZN HRę DBWZQV. ŚDRVGMZ ILYLGZ, GVIZA AMZNB POFXA, AMZNB QęABP...\n\nhFYQVXG: kZHHDLIW\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nuILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\n\n## gzhp: GZHP7\n\nDSVIV \"oZMTFZTV\" RH GSV MZNV LU GSV IRTSG OZMTFZTV.\n`UIVJFLM(HFYQVXG = \"iV: oZMTFZTV RM ZMW NVHHZTV\", XLMGVMG = \"oZMTFZTV\")`\nhVMW FH BLFI GSLFTSGH! gBKV\n\nGSV WRHGIRYFGRLM LU GSV OVMTGSH RM LFI NVHHZTV?\nsLD WL BLF GSRMP: DSRXS UILN GSV ZOO WRHGIRYFGRLMH RH NLHG HRNROZI GL\nDSZG GSV OZMTFZTV DZH FHVW GL KIVKZIV GSV HVXLMW NVHHZTV.\nZOHL HVV GSVN RM BLFI NZTRX KILTIZN :k). mLD DV XZM RMEVHGRTZGV\ndVOO WLMV! gSZMPH GL BLFI IVHFOGH DV LYGZRM VCXVOOVMG YZIKOLGH (BLF XZM KILYZYOB\n\nhFYQVXG: oZMTFZTV RM GSV NVHHZTV\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nuILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\n\n## gzhp: GZHP6\n\nGSV HRNROZIRGRVH YVGDVVM WRHGIRYFGRLM LU GSV OVMTGSH RM LFI NVHHZTV ZMW PMLDM OZMTFZTVH.\ngSZMPH GL GSRH WZGZ DV DLFOW YV ZYOV GL KIVKZIV XLFKOV YZIKOLGH GL XLMXOFWV ZYLFG\n\nkOVZHV, IVNVNYVI GL MZNV GSRH ORHG DRGS IVHKVXGREV OZMTFZTVH!\n`DRPR_OVMTGSH` RH GSV ORHG LU GZYVOVW OVMTGS LU ZOO DLIWH ULI VZXS OZMTFZTV.\n`OVMTGSH` RH GSV EVXGLI LU GZYVOVW OVMTGS LU ZOO DLIWH.\n`UIVJFLM(HFYQVXG=\"iV: oVMTGSH RM GSV GVCG\", XLMGVMG = `OVMTGSH`, ZGGZXSNVMG = `DRPR_OVMTGSH`)`.\nhVMW FH BLFI IVHFOGH:\n\nBLF PMLD HLNV UZHG DZB GL (.... XLś YBOV MRV WL GSRH).\ngSRH RH SFTV QLY GL NVZHFIV GSV OVMTGS LU VZXS DLIW ULI ZOO OZMTFZTVH, YFG DV YVORVEV\n\ndV SLKV GSRH RH VMLFTS ULI LFI MVVWH.\nkOVZHV, URMW GSV `DRPRJFLGVH` ZGGZXSNVMG. gSVIV RH Z ORHG LU JFLGVH ULI NZMB OZMTFZTVH.\nDRPRKVWRZ IVHLFIXVH, HL DV XZM HSZIV RG DRGS BLF.\nSFTV ZNLFMG LU DLIWH RM KOVMGB OZMTFZTVH. rG`H QFHG ZH DVOO DV SZEV Z HZNKOV UILN\nGSVN DRGS GSV OVMTGSH LU DLIWH RM OZMTFZTVH GSZG DV PMLD! mZGFIZOOB DV MVVW HLNV\nPMLD SLD NZMB DLIWH SZH GSV OVMTGS LU 1, 2, 3, ZMW HL LM, DV XLFOW XLNKZIV\nXRKSVIVW NVHHZTV. zOO BLF MVVW GL WL RH GL NVZHFIV GSV OVMTGS LU VZXS DLIW. rU DV DLFOW\nwLM`G DLIIB, DV PMLD HLNV HRNKOV RWVZ SLD GL IVXLTMRAV GSV OZMTFZTV LU GSV ZMB\n\nxZM BLF IVXLTMRAV GSV OZMTZTFV?\nYFG GFIMH LFG RG DZH DIRGGVM RM HLNV OZMTFZTV DV FMULIGFMZGVOOB WLM`G PMLD.\nlYERLFHOB GSRH NVHHZTV RH ZOHL XRKSVIVW. dV GIRVW GL FHV GSV PVB\n\nhFYQVXG: oVMTGSH RM GSV GVCG\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nuILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\n\n## gzhp: GZHP5\n\ndV DLFOW YV TIZGVUFO.\n\nDSVIV \"c\" RH GSV MZNV LU GSZG NVHHZTV BLF ZIV ZYOV GL FMOLXP.\n\n          XLMGVMG = \"xLMGVMG LU GSV FMOLXPVW NVHHZTV\")`\n`UIVJFLM(HFYQVXG = \"iV: mVCG GVCG: c\",\nkOVZHV, HVMW FH IVKOB:\n\ndLFOW BLF SZEV ZXXVHH GL GSVN MLD?\nGL XRKSVIV GSV MZNVH LU GDL IVNZRMRMT NVHHZTVH?\ndSZG WL BLF GSRMP ZYLFG KLHHRYRORGB GSZG LFI UIRVMW FHVW GSV PVB\n\ngSVIV NFHG YV HLNV XOFV RM GSRH NVHHZTV...\nsLDVEVI GSVIV RH ML KZHHDLIW RM SVIV.\n\nvCXVOOVMG DLIP, BLF SZEV XIZXPVW GSV XLWV!\n\nhFYQVXG: mVCG GVCG\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nuILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\n\n## gzhp: GZHP4\n\nDSVIV `LOW` ZIV GSV OVGGVIH RM GSV XLWV`H HVMHV ZMW `MVD` ZIV URGGVW IVZO OVGGVIH.\n`UIVJFLM( HFYQVXG=\"iV: pVB\", XLMGVMG=X(LOW = \"ZYXWVU....A\", MVD = \"MVDOVGGVIHIVHKVXGREVOB\"))`\ngBKV:\n\ngZPV ZWEZMGZTV LU `GLK100XLNNLMdLIWH`.\n\nIAVXALDMRPZNR?\nKLKIZDRVMRZ. gV PGóIV KLQZDRZQą HRę MZQIAZWARVQ YBć NLżV Hą łZGDL ILAKLAMZDZOMBNR\naORXANB DHABHGPRV DBIZAB, GV, PGóIV KLQZDRZQą HRę MZQXAęśXRVQ HZ WOZ MZH łZGDV WL\n\ngSVIV RH LMV RWVZ SLD GL WL GSRH.\n\nNRHGIZMHOZGVW.\nXLIIVXG, ZMW DV MVVW GL RMEVHGRTZGV GSVHV OVGGVIH, GSZG DVIV\nOLLPRMT HGIZMTV. rG NVZMH GSZG LFI PVB RH MLG UFOOB\nGSVIV ZIV VEVM HLNV DLIWH DV PMLD. yFG GSVIV ZIV ZOHL HGROO DLIWH,\ndVOO WLMV! mLD DV ZIV HL XOLHV! lFI NVHHZTV OLLPH Z ORGGOV YRG UZNRORZI,\n\nhFYQVXG: pVB\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nuILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\n\n## gzhp: GZHP3\n\nyVHG IVTZIWH!\n\ndV DRHS BLF OFXP!\nhVMW FH IVKOB: `UIVJFLM(HFYQVXG = \"iV: gIZMHXIRKGRLM\", XLMGVMG = \"GVCGBLFDROOTVG\")`.\n\nVMTORHS OVGGVIH. xZM BLF HSLD FH BLFI IVHFOGH?\nmLD BLF XZM HFYHGRGFGV LOW XRKSVIVW OVGGVIH DRGS GSV MVD\n\nUIVJFVMXRVH LU OVGGVIH RM GSV VMTORHS OZMTFZTV.\nGSV `vMTORHSoVGGVIuIVJFVMXB` WZGZHVG. rG XLMGZRMH IVOZGREV\nVMTORHS UIVJFVMXRVH LU OVGGVIH. dV SZEV KIVKZIVW ZMW ZGGZXSVW\nZMW DSRXS ZIV GSV OVZHG XLNNLM, DV XZM XLNYRMV GSVN DRGS PMLDM\ntIVZG QLY! mLD, DSVM DV PMLD DSRXS OVGGVIH ZIV FHVW NLHG LUGVM\n\nhFYQVXG: gIZMHXIRKGRLM\ngL: X81632WXV28XZ740U2U2503656U3W62Z@NZRO.GLI\nuILN: 154VY7278UX44650YWW2YY39YY2Y5X69@NZRO.GLI\n\n## gzhp: GZHP2\n\nkOVZHV, IVNVNYVI GL MZNV GSRH EVXGLI DRGS IVHKVXGREV OVGGVIH!\nDROO URMRHS. `UIVJ` RH GSV EVXGLI LU UIVJFVMXRVH ULI VZXS OVGGVI.\nhVMW FH IVKOB: `UIVJFLM(HFYQVXG = \"iV: uIVJFVMXRVH\", XLMGVMG = `UIVJ`)` ZH HLLM ZH BLF\n\nGSZG DLFOW YV ZDVHLNV (GL GIAVYZ ANRVMRX :k).\nRM VMTORHS, HL RU BLF XLFOW URMW GSV UIVJFVMXRVH RM GSV NVHHZTVH,\ndV ZIV TLRMT GL KIVKZIV WZGZ ZYLFG UIVJFVMXRVH LU OVGGVIH\n\nOVGGVI UIVJFVMXRVH! hL OVG`H GL GSRH!\nGSV NVHHZTV, DV XLFOW XLNKZIV GSVN DRGS PMLDM VMTORHS\nNLHG LUGVM. rU DV DLFOW PMLD SLD LUGVM VZXS OVGGVI RH FHVW RM\n`R` WLVH`G. rM VMTORHS OZMTFZTV OVGGVI `V` DLFOW LXXFIVH\nyFG OVG`H GZPV Z OLLP, GSV `K` OVGGVI ZKKVZIH EVIB LUGVM. zMW\n\nNVHHZTV, RU LMOB DV XLFOW PMLD GSV PVB...\nRH GL OLMT GL YV LMV KZHHDLIW DV ZIV HVVPRMT. gSRH NFHG YV HLNV XLWVW"
 ), .Names = c("intro", "task1", "task2", "task3", "task4", "task5",
               "task6", "task7", "outro", "hint1", "hint2", "hint4", "hint5",
               "hint6", "hint7", "errorIntro", "errorNAs", "errorFrequencies",
               "errorNoNAMES", "errorLetters", "errorDecipher", "errorKey1",
               "errorKey2", "errorBadKey", "errorBadX", "errorBadX2", "errorBadAND",
               "errorWikiNames", "errorLengths", "errorLanguage", "errorEnd",
               "errorAttachment", "errorContent", "errorSubject"))

 subjects <- c('0' = 're: asking for help',
               '1' = 're: frequencies',
               '2' = 're: transcription',
               '3' = 're: key',
               '4' = 're: next text: and',
               '5' = 're: lengths in the text',
               '6' = 're: language in and message',
               '7' = 're: password')
 if( length(args) == 0 ){
   cat(txt$intro)
   level <<- 0
 } else{
     if(!is.null(args$hint) && args$hint == TRUE) hintf(txt$level) else {
       if( tolower(args$subject) == subjects[1] ){
         if( digest(args$content) == "6ba57621bc24fe10f21bc8ff7c178b39" ){
           level <<- 1
           taskf(level)
         } else if(level == 0) cat(txt$errorIntro)
       }
       # 1. podaj wektor częstości
       if( tolower(args$subject) == subjects[2] ){
         if(is.null(names(args$content))){
           cat(txt$errorNoNAMES)
         } else{
           if( any(is.na(args$content)) || any(is.na(names(args$content))) )
             cat(txt$errorNAs) else{
               if(!all(names(args$content[letters])==letters))
                 cat(txt$errorLetters)
               if( digest(args$content[letters]) == 'cf9f65b80d343b29860fb6cf10b644d4' ){
                 level <<- 2  # przypisanie podwójne, żeby w każdej chwili można było
                 # wywołać hinta dla odpowiedniego poziomu gry.
                 taskf(level)
               } else cat(txt$errorFrequencies)
             }
         }
       }
       ## 2. podstaw literki z EnglishLetterFrequency
       if( tolower(args$subject) == subjects[3] ){
         In <- gsub("[^A-Z]","", toupper(args$content))
         if( digest(In) == 'd5bc6f3d64e0199e08d029ee25d835a2' ){
           level <<- 3
           taskf(level)
         } else cat(txt$errorDecipher)
       }
       ## 3. przetłumacz WSZYSTKIE literki (znajdź pełny klucz)
       if( tolower(args$subject) ==  subjects[4] ){
         if( any(names(args$content) != c("old","new")) | length(args$content) != 2 )
           cat(errorKey1) else{
             if( any(nchar(args$content) != c(26,26)) )
               cat(txt$errorKey2) else{
                 ## dopuszczam, że gracz może nie podać liter we wskazanej kolejności "abc...xyz"
                 ## jeśli tylko podaje je poprawnie.
                 ord <- order( strsplit(args$content['old'], "")[[1]] )
                 In <- strsplit(args$content['new'], "")[[1]][ord]
                 if( digest(In) == '277d35cce1043607f15f83fbc36b75ff' ){
                   level <<- 4
                   taskf(level)
                 } else cat(txt$errorBadKey)
               }
           }
       }
       ## 4. znajdź kolejny szyfr
       if( tolower(args$subject) == subjects[5] ){
         if( strsplit(args$subject, " ")[[1]][3] %in% c('and', 'guns') ){
           cat(txt$errorBadX)
         } else {
           if( strsplit(args$subject, " ")[[1]][3] == "guns" ){
             cat(txt$errorBadX2)
           }
         }
         In <- gsub("[^A-Z]","", toupper(args$content))
         if( digest(In) == 'e876c26d9d8bad8028cefb95eb54df21' ){
           level <<- 5
           taskf(level)
         } else cat(txt$errorBadAND)
       }
       ## 6. zlicz długości słów
       if( tolower(args$subject) == subjects[6] ){
         if( ! any(names(args) %in% "attachment") ){
           cat(txt$errorAttachment)
         } else {
           if( !all(names(args$attachment) %in% names(wikiquotes)) ){
             cat(txt$errorWikiNames)
           }
           if( digest(args$content[as.character(1:13)]) == "0aac2628993a796da4b5408f8f9d0ef1" &&
               digest(args$attachment[names(wikiquotes)]) == "6e6b01872252d622733fcc3e0d29eee6" ){
             level <<- 6
             taskf(level)
           } else cat(txt$errorLengths)
         }
       }
       ## 7.  podanie języka
       if( tolower(args$subject) == subjects[7] ){
         if( digest(tolower(args$content)) == '939ad54fa39990afd160056465120f72'){
           level <<- 7
           taskf(level)
         } else cat(txt$errorLanguage)
       }
       ## 8. podanie hasła
       if( tolower(args$subject) == subjects[8] ){
         if( digest(args$content) == 'ba61e613c2207f0a81e0697914f3dc96' )
           cat(txt$outro) else cat(txt$errorEnd)
       }
     }
   }
 if( length(args)>0 && !c("content")%in%names(args) && names(args)!='hint')
   cat(txt$errorContent)
 if( length(args)>0 && !c("subject")%in%names(args) && names(args)!='hint')
   cat(txt$errorSubject)

}

